/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ekonuma

import com.ekonuma.Quiz.StudentProgress.printProgressBar
import com.ekonuma.Quiz.StudentProgress.progressText

//データクラス
//汎用 （ジェネリック）
data class Question<T>(
    val questionText: String,
    val answer: T,
    val difficulty: Difficulty
)

//列挙型
enum class Difficulty {
    EASY, MEDIUM, HARD
}

class Quiz {
    val question1 = Question<String>("Quoth the raven ___", "nevermore", Difficulty.MEDIUM)
    val question2 = Question<Boolean>("The sky is green. True or false", false, Difficulty.EASY)
    val question3 = Question<Int>("How many days are there between full moons?", 28, Difficulty.HARD)

    //オブジェクト
    companion object StudentProgress {
        fun StudentProgress.printProgressBar() {
            repeat(Quiz.answered) { print("▓") }
            repeat(Quiz.total - Quiz.answered) { print("▒") }
            println()
            println(Quiz.progressText)
        }
        val StudentProgress.progressText: String
            get() = "${Quiz.answered} of ${Quiz.total} answered."
        var total: Int = 10
        var answered: Int = 3
    }
}

fun main() {
    val quiz = Quiz()
    println("${quiz.question1} ${quiz.question2} ${quiz.question3}")
    println(Quiz.progressText)
    println(Quiz.printProgressBar())
}


